### ISSUE TITLE
SCAN Workflow Documentation

### ISSUE THREAD

**Issue by blairdrummond** [dacostalab/scbursts#31]
@mdext070 Can you write a little explanation up in 

https://github.com/dacostalab/scbursts/blob/15e544622e5f36e07c6d97d6bc239a3a5f92ebee/vignettes/scbursts.Rmd#L27

to explain the handling of QUB, xlsx, and most importantly SCAN files? It's an R markdown document that generates the "soft manual", but you're more familiar with how these file formats work, so you would be better equipped to write a short blurp about them.

You'll need LaTeX (= `texlive-full` in ubuntu) and `pandoc` (also in the ubuntu repos) to generate those pdfs, but if you just write something I can fix up the syntax later.

[scbursts.pdf](https://github.com/dacostalab/scbursts/files/2683898/scbursts.pdf)

**Comment by mdext070** [comment]
Sure thing. I will work on this early this week.
