### ISSUE TITLE
Error in clampfit.read()

### ISSUE THREAD

**Issue by blairdrummond** [dacostalab/scbursts#35]

**Comment by blairdrummond** [comment]
The recent update 08f935f to clampfit caused the program to not compile -- there are some files that seem to have a header (such as the included example file). Can you forward me the files that you were testing against? I'll get a solution up that works for both files. @mdext070

**Comment by mdext070** [comment]
Hey Blair,

Here is the file I was testing with. This one should work.

If you want to work out a solution for the header, go for it. However, I
don't think it is necessary. The "header" from the original example file
was actually manually added by Michel. When extracting results from
clampfit into an excel spreadsheet, there is no header. Excel spreadsheets
from clampfit contain only columns with data.

Cheers,

Mat
